apiVersion: v1
kind: ServiceAccount
metadata:
    name: runner-pod-npu-scheduler
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: runner-pod-npu-scheduler-clusteradmin
subjects:
    - kind: ServiceAccount
      name: runner-pod-npu-scheduler
      namespace: kube-system
roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
